public enum CarTypeShop {
    BMW_M3_E30 = 0,
    Audi_Quattro = 1,
    Fiat131 = 2,
    LanciaSratos = 3,
    LanciaS4 = 4,
    HyperSportOne = 5,
    Ford_RS200 = 6,
    Ford_Cosworth = 7,
    Mitsubishi_Lancer = 8,
    Lancia_Delta = 9,
    Mini_Cooper = 10,
    Ford_Escort_RS1800 = 11,
    Lancia_Fulvia = 12,
    Peugeot_205 = 13,
    Subaru_Impreza = 14,
    Porsche_959 = 15,
    Renault_Alpine = 16,
    Renault_R5 = 17,
    HyperSportOne_One_point_two = 18,
    Ford_Mustang_Red = 19,
    ToyotaCilica = 20,
}